### PR TITLE
Add Rule custom module

### PR DESCRIPTION
**Pull request by fukagawa-satoru**
Thank you for making IBLinter. I added rule of Custom Module. Rule of Custom Module reduces mistake of custom Module form on IB. Please add this function to IBLinter by all means.

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@fukagawa-satoru Thank you for your pr.

**Comment by fukagawa-satoru** [comment]
@kateinoigakukun Thank you! I added test case.

**Comment by fukagawa-satoru** [comment]
If user mistake custom Module form in IB, the view is created UIKit's view instead of custom class. It is important problem. so rule of Custom Module is prevent the probrem.

https://stackoverflow.com/questions/24924966/xcode-6-bug-unknown-class-in-interface-builder-file

**Comment by kateinoigakukun** [comment]
LGTM!

**Pull request merged**
